image:
  repository: artifactory.dagility.com/docker/vdchechghpx-frontend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: vdchechghpx-frontend-habitat-firstonere.dagility.com
    paths:
    - /
serviceAccount:
  create: false
